const products = [
    {
        id: 0,
        name: "Egg",
        price: 197.99,
        instock: 3,
        filter: "other", 
        imgSrc: "./images/egg-removebg-preview.png",
    },
    {
        id: 1,
        name: "Mug 1",
        price: 12.38,
        instock: 3,
        filter: "mugs", 
        imgSrc: "./images/mug1-removebg-preview.png",
    },
    {
        id: 2,
        name: "Vase 6",
        price: 159.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase6-removebg-preview.png",
    },
    {
        id: 3,
        name: "Mug 4",
        price: 19.99,
        instock: 3,
        filter: "mugs", 
        imgSrc: "./images/mug4-removebg-preview.png",
    },
    {
        id: 4,
        name: "Mug 2",
        price: 15.99,
        instock: 3,
        filter: "mugs", 
        imgSrc: "./images/mug2-removebg-preview.png",
    },
    {
        id: 5,
        name: "Vase 1",
        price: 129.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase1-removebg-preview.png",
    },
    {
        id: 6,
        name: "Vase 5",
        price: 168.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase5-removebg-preview.png",
    },
    {
        id: 7,
        name: "Vase 2",
        price: 119.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase2-removebg-preview.png",
    },
    {
        id: 8,
        name: "Teapot",
        price: 199.99,
        instock: 3,
        filter: "cookware", 
        imgSrc: "./images/teapot-removebg-preview.png",
    },
    {
        id: 9,
        name: "Vase 7",
        price: 139.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase7-removebg-preview.png",
    },
    {
        id: 10,
        name: "Vase 3",
        price: 149.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase3-removebg-preview.png",
    },
    {
        id: 11,
        name: "Vase 8",
        price: 127.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase8-removebg-preview.png",
    },
    {
        id: 12,
        name: "Mug 6",
        price: 11.99,
        instock: 3,
        filter: "mugs", 
        imgSrc: "./images/mug6-removebg-preview.png",
    },
    {
        id: 13,
        name: "Vase 9",
        price: 189.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase9-removebg-preview.png",
    },
    {
        id: 14,
        name: "Mug 3",
        price: 13.99,
        instock: 3,
        filter: "mugs", 
        imgSrc: "./images/mug3-removebg-preview.png",
    },
    {
        id: 15,
        name: "Vase 4",
        price: 169.99,
        instock: 3,
        filter: "vases", 
        imgSrc: "./images/vase4-removebg-preview.png",
    },
    {
        id: 16,
        name: "Mug 5",
        price: 8.99,
        instock: 3,
        filter: "mugs", 
        imgSrc: "./images/mug5-removebg-preview.png",
    },
];